version: '3'

services: 

  back-end:
    build: 
      context: backend
    container_name: back-end
    working_dir: /opt/app
    networks: 
      - node-network
    tty: true
    ports: 
      - "4200:4200"
    command: node api.js

  front-end:
    build: 
      context: frontend
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  nginx:
    build: 
      context: .
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - back-end
       - front-end
  
networks: 
  node-network:
    driver: bridge